{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "cicdhelm1.serviceAccountName" . }}
  labels:
{{ include "cicdhelm1.labels" . | indent 4 }}
{{- end -}}
